apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2026-04-12T02:42:38Z"
  generation: 1
  labels:
    app: redis
  name: redis
  namespace: video-compress
  resourceVersion: "1394557"
  uid: 23a8bba4-8c4a-4a85-8fbb-f0609a6c7086
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
